#ttv_user:
 #   resource: "@TTVUserBundle/Resources/config/routing.yml"
  #  prefix:   /

ttv_website:
    resource: "@TTVWebsiteBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

login:
    path: /login
    defaults:
        _controller: TTVUserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout