# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        TTV\UserBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_ADMIN:        ROLE_USER
        ROLE_SUPER_ADMIN:  [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    providers:
        main:
           entity:
              class: TTV\UserBundle\Entity\User
              property: username


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        main_login:
            pattern: ^/login$
            anonymous: true
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            provider: main
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:       logout
                target:     login

access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
