<?php

namespace TTV\WebsiteBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * TrickRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrickRepository extends EntityRepository
{
    public function getTrick($id)
    {
        $query = $this->createQueryBuilder('t')
                    ->leftJoin('t.user', 'u')
                    ->addSelect('u')
                    ->leftJoin('t.comments', 'co')
                    ->addSelect('co')
                    ->leftJoin('t.category', 'c')
                    ->addSelect('c')
                    ->leftJoin('t.im', 'i')
                    ->addSelect('i')
                    ->where('t.id = :id')
                    ->setParameter('id', $id)
                    ->getQuery();
        return $query->getOneOrNullResult();


    }
    public function getAllTricks($page, $nbPerPage)
    {
        $query = $this  ->createQueryBuilder('t')
                        ->leftJoin('t.image', 'i')
                        ->addSelect('i')
                        ->leftJoin('t.user', 'u')
                        ->addSelect('u')
                        ->leftJoin('t.category', 'c')
                        ->addSelect('c')
                        ->orderBy('t.date', 'DESC')
                        ->addOrderBy('t.updatedAt', 'DESC')
                        ->getQuery();

        $query  ->setFirstResult(($page-1) * $nbPerPage)
                ->setMaxResults($nbPerPage);

        return new Paginator($query, true);
    }
}
